import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
        <li>
          <Link to="/">DesktopEightOne</Link>
        </li>
        <li>
          <Link to="/desktopthirteentwo">DesktopThirteenTwo</Link>
        </li>
        <li>
          <Link to="/desktopfifteen">DesktopFifteen</Link>
        </li>
        <li>
          <Link to="/desktoponeone">DesktopOneOne</Link>
        </li>
        <li>
          <Link to="/desktopeight">DesktopEight</Link>
        </li>
        <li>
          <Link to="/desktopseventeen">DesktopSeventeen</Link>
        </li>
        <li>
          <Link to="/desktopthirtysevenone">DesktopThirtySevenOne</Link>
        </li>
        <li>
          <Link to="/desktopfortyseven">DesktopFortySeven</Link>
        </li>
        <li>
          <Link to="/desktopthirteen">DesktopThirteen</Link>
        </li>
        <li>
          <Link to="/desktopthirtyseventwo">DesktopThirtySevenTwo</Link>
        </li>
        <li>
          <Link to="/desktopfortyeightone">DesktopFortyEightOne</Link>
        </li>
        <li>
          <Link to="/desktopfortynineone">DesktopFortyNineOne</Link>
        </li>
        <li>
          <Link to="/desktopfifty">DesktopFifty</Link>
        </li>
        <li>
          <Link to="/regsitroone">RegsitroOne</Link>
        </li>
        <li>
          <Link to="/desktopeighttwo">DesktopEightTwo</Link>
        </li>
        <li>
          <Link to="/desktopthirteenone">DesktopThirteenOne</Link>
        </li>
        <li>
          <Link to="/desktopthirtyseven">DesktopThirtySeven</Link>
        </li>
        <li>
          <Link to="/desktopfortyeight">DesktopFortyEight</Link>
        </li>
        <li>
          <Link to="/desktopfortynine">DesktopFortyNine</Link>
        </li>
        <li>
          <Link to="/desktopfiftyone">DesktopFiftyOne</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
